version: '3.1'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7114
    ports:
      - 3307:3306
    volumes:
      - ./docker/database/data.sql:/docker-entrypoint-initdb.d/data.sql
  springboot-app:
    # container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    image: springbooot-app
    restart: always
    ports:
      - 8000-8999:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/clustereddatawarehouse
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=7114

